import Config

# Configure your database
config :twilixir_bot, TwilixirBot.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "10.0.0.3",
  database: "twilixir_bot_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :twilixir_bot, TwilixirBot.Services,
  twitch_client_id: "0m4fl0b3v5qtp0zln4yqh6b6ipjke7",
  twitch_client_secret: "wzoy11fxuiqxucjaw60fe1imrtetl3",
  twitch_redirect_uri: "http://localhost:4000/oauth/callback",
  twitch_bot_refresh_token: "s4fxjot0fvunv4o6huq8rh8q9y4dh6c7g9nkrrjhgybsw0yef2",
  twitch_irc_uri: "wss://irc-ws.chat.twitch.tv:443"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :twilixir_bot_web, TwilixirBotWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "5x0pJRb1W6tGVmLoTPtT83CzCKocQ6sT1G0iHFSIWvheaoBJ80Or86PoWNx5u4TA",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :twilixir_bot_web, TwilixirBotWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/twilixir_bot_web/(live|views)/.*(ex)$",
      ~r"lib/twilixir_bot_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
